### ISSUE TITLE
issues with '\' and '/' when running on windows

### ISSUE THREAD

**Issue by vainaijr** [wyharveychen/CloserLookFewShot#10]
please fix this issue

**Comment by ycliu93** [comment]
I would suggest using Ubuntu as the development environment.

**Comment by vainaijr** [comment]
warnings.warn("The use of the transforms.Scale transform is deprecated, " +
Traceback (most recent call last):
  File "./train.py", line 145, in <module>
    os.makedirs(params.checkpoint_dir)
  File "/home/vainaijr/anaconda3/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/vainaijr/anaconda3/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/vainaijr/anaconda3/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 3 more times]
  File "/home/vainaijr/anaconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/work'

permission error on ubuntu

**Comment by ycliu93** [comment]
Please check the permission of your directory. Use chmod to fix it.

**Comment by vainaijr** [comment]
I might be doing something wrong but, why is it giving this as the params checkpoint directory

/work/newriver/wyharveychen/CloserLookFewShot//checkpoints/CUB/Conv4_baseline

/work/newriver/whharveychen?

**Comment by MichalisLazarou** [comment]
what should the permission be?? I also get the same error exactly

**Comment by vainaixr** [comment]
I think I changed config.py file, it has ‘ /work/newriver/wyharveychen/CloserLookFewShot/’ in save directory, I changed it to a different path.
