### ISSUE TITLE
test.csv is unavailable 

### ISSUE THREAD

**Issue by caddyless** [wyharveychen/CloserLookFewShot#22]
I try to run script 'download_miniImagenet.sh' and the program broke down with error messages below:

--2019-05-27 09:53:56--  https://raw.githubusercontent.com/twitter/meta-learning-lstm/master/data/miniImagenet/test.csv%0D
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.76.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.76.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 09:53:56 ERROR 404: Not Found.

': [Errno 2] No such file or directorygenet_filelist.py
': [Errno 2] No such file or directoryilelist.py

I think the main problem is file 'test.csv' is not available on server. If my guess is correct, could you please upload this file to github since it is not so big? If there are other causes, could you give me a hand? Thanks

**Comment by ebennequin** [comment]
Hi,
The script works for me, the file test.csv is available on server. Where does "%0D" comes from at the end of your link ?

**Comment by wyharveychen** [comment]
You can also directly go to the GitHub page to download it.
https://github.com/twitter/meta-learning-lstm/tree/master/data/miniImagenet

**Comment by caddyless** [comment]
> Hi,
> The script works for me, the file test.csv is available on server. Where does "%0D" comes from at the end of your link ?

Thanks for your comment.

This error message was generated by my shell, and I just copied it to here. I didn't notice '%0D' was attached behind original link, and it may be the cause. But I'm sure that the redundant string doesn't exist in my script and it throws error message above when I run. I copied the link of test.csv to my web browser and it throw '404 not found' to me yesterday. However it works well now. I think there may be something wrong with my network yesterday but it restores now.

**Comment by caddyless** [comment]
> You can also directly go to the GitHub page to download it.
> https://github.com/twitter/meta-learning-lstm/tree/master/data/miniImagenet

Thanks for your help

**Comment by johnnyasd12** [comment]
Hi, I try to download and preprocess the miniImageNet refer to #29 instead of original ImageNet because it's too large, and I download train.csv, val.csv, test.csv from the link: https://github.com/twitter/meta-learning-lstm/tree/master/data/miniImagenet

But I got the following error:
> Traceback (most recent call last):
  File "write_miniImagenet_filelist.py", line 47, in <module>
    fname_number = [ int(re.split('_|\.', fname)[1]) for fname in fnames]
  File "write_miniImagenet_filelist.py", line 47, in <listcomp>
    fname_number = [ int(re.split('_|\.', fname)[1]) for fname in fnames]
ValueError: invalid literal for int() with base 10: 'jpg'

Is there any problem in my procedure?
