### ISSUE TITLE
pytorch version

### ISSUE THREAD

**Issue by mileyan** [wyharveychen/CloserLookFewShot#3]
Hi,
It is a nice work. 
Now I am facing some problems when running your code. So I want to make sure that I use the same pytorch as you. Which pytorch version did you use when you implement this project?

**Comment by wyharveychen** [comment]
Hello,
My Pytorch version is 0.3.1, but I have also tested on 1.0 and it works.
What does your error message say?

**Comment by Wann-Jiun** [comment]
It's a nice work+1 
Just changed "loss.dada[0]" to "loss.item()" in baselinetrain.py and it seems to work fine. I am using 1.0.1.post2 (pytorch version).

**Comment by apple2373** [comment]
I'm got the following error with 1.0.1.post2. 

Traceback (most recent call last):
  File "./train.py", line 177, in <module>
    model = train(base_loader, val_loader,  model, optimization, start_epoch, stop_epoch, params)
  File "./train.py", line 32, in train
    model.train_loop(epoch, base_loader,  optimizer ) #model are called by reference, no need to return 
  File "/nfs/tynamo/home/data/vision7/stsutsui/public_repos/CloserLookFewShot/methods/baselinetrain.py", line 44, in train_loop
    avg_loss = avg_loss+loss.data[0]
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

Well, I was so lazy to fix "loss.dada[0]" to "loss.item()" by myself, and didn't want to change the code without the author's confirmation so I installed 0.3.1 using the following command, then it worked. 

conda install pytorch==0.3.1 torchvision -c pytorch

**Comment by russell0** [comment]
> It's a nice work+1
> Just changed "loss.dada[0]" to "loss.item()" in baselinetrain.py and it seems to work fine. I am using 1.0.1.post2 (pytorch version).

well... at least dada -> data.
