### ISSUE TITLE
test.py _ classifier.weight

### ISSUE THREAD

**Issue by BoostMom** [wyharveychen/CloserLookFewShot#36]
hello,

      very nice work~
      I am running the demo with CUB data, however, in test stage, an error happend:(And I found that the code just updated a day ago~)
      
Traceback (most recent call last):
  File "test.py", line 108, in <module>
    model.load_state_dict(tmp['state'])
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BaselineFinetune:
	Unexpected key(s) in state_dict: "classifier.weight", "classifier.bias".

**Comment by wyharveychen** [comment]
Hello, I have corrected it. Please use the new test.py, thanks!
